"""Inicial

Revision ID: 9d7412dccf55
Revises: 
Create Date: 2026-03-21 12:43:00.683920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d7412dccf55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agrupaciones',
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('subdominio', sa.String(length=100), nullable=True),
    sa.Column('cif', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('cp', sa.String(length=10), nullable=True),
    sa.Column('poblacion', sa.String(length=40), nullable=True),
    sa.Column('provincia', sa.String(length=40), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('web', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uix_agrupacion_slug'),
    sa.UniqueConstraint('subdominio', name='uix_agrupacion_subdominio')
    )
    op.create_table('permisos',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=True),
    sa.Column('es_root', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uix_email_usuario')
    )
    op.create_table('auditorias',
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=True),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuraciones_agrupaciones',
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=50), nullable=True),
    sa.Column('sufijo', sa.String(length=10), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=True),
    sa.Column('color_secundario', sa.String(length=7), nullable=True),
    sa.Column('color_fondo', sa.String(length=7), nullable=True),
    sa.Column('color_texto', sa.String(length=7), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agrupacion_id', name='uix_agrupacion_configuracion')
    )
    op.create_table('invitaciones',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('aceptada', sa.Boolean(), nullable=True),
    sa.Column('expira_en', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uix_token_invitacion')
    )
    op.create_table('roles',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subagrupacion',
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membresias',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('agrupacion_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_by', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agrupacion_id'], ['agrupaciones.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_permisos',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('rol_id', 'permiso_id')
    )
    op.create_table('membresias_permisos',
    sa.Column('membresia_id', sa.Integer(), nullable=False),
    sa.Column('permiso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['membresia_id'], ['membresias.id'], ),
    sa.ForeignKeyConstraint(['permiso_id'], ['permisos.id'], ),
    sa.PrimaryKeyConstraint('membresia_id', 'permiso_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('membresias_permisos')
    op.drop_table('roles_permisos')
    op.drop_table('membresias')
    op.drop_table('subagrupacion')
    op.drop_table('roles')
    op.drop_table('invitaciones')
    op.drop_table('configuraciones_agrupaciones')
    op.drop_table('auditorias')
    op.drop_table('usuarios')
    op.drop_table('permisos')
    op.drop_table('agrupaciones')
    # ### end Alembic commands ###
